### ISSUE TITLE
watch: Support self-signed certificates

### ISSUE THREAD

**Issue by brianmartin** [mkokho/kubemrr#3]
I'm very excited about this tool. Our dev cluster is using a self-signed certificate though. 

It would be nice to have a `--no-verify` flag for watch.

Currently get: 
```
x509: certificate signed by unknown authority
```

**Comment by mkokho** [comment]
Okay, I will add it after the weekend. Not because I'm lazy, but because I will be away from the computer ;)

**Comment by brianmartin** [comment]
@mkokho Awesome, much appreciated. (Eventually I'll make myself useful by getting up-to-speed on Go :p)

**Comment by mkokho** [comment]
@brianmartin, please try the binary from this tag: https://github.com/mkokho/kubemrr/tree/v1.2.0-beta1

I have disabled verification by default because it seems strange for me that a Kube API Server can be visible to a public network. Please, correct me if I'm missing something, and I will add `--no-verify` flag.

**Comment by brianmartin** [comment]
@mkokho Hey, I really appreciate the changes. I have tested and verified that rhe transport layer is now working.

**Comment by mkokho** [comment]
Small change in v1.2.0, comparing to v1.2.0-beta:
- verification is now configured by field `insecure-skip-tls-verify` in kubeconfig file, like this:
```
clusters:
- name: cluster_2
  cluster:
    server: https://bar.com
    certificate-authority: ca2
    insecure-skip-tls-verify: true
```
